[app]
overall = { bg = "#161616" }

[mgr]
cwd = { fg = "#cecece" }

find_keyword  = { fg = "#c39900", italic = true }
find_position = { fg = "#aeaeae", bg = "reset", italic = true }

marker_copied   = { fg = "#5bb661", bg = "#5bb661" }
marker_cut      = { fg = "#ed756e", bg = "#ed756e" }
marker_marked   = { fg = "#00baaa", bg = "#00baaa" }
marker_selected = { fg = "#3ba6f5", bg = "#3ba6f5" }

count_copied   = { fg = "#161616", bg = "#5bb661" }
count_cut      = { fg = "#161616", bg = "#ed756e" }
count_selected = { fg = "#161616", bg = "#3ba6f5" }

border_symbol = "│"
border_style  = { fg = "#3a3a3a" }

[tabs]
active   = { fg = "#eeeeee", bg = "#2e2e2e", bold = true }
inactive = { fg = "#808080", bg = "#222222" }

[mode]
normal_main = { fg = "#161616", bg = "#3ba6f5", bold = true }
normal_alt  = { fg = "#3ba6f5", bg = "#222222" }

select_main = { fg = "#161616", bg = "#5bb661", bold = true }
select_alt  = { fg = "#5bb661", bg = "#222222" }

unset_main = { fg = "#161616", bg = "#ed756e", bold = true }
unset_alt  = { fg = "#ed756e", bg = "#222222" }

[indicator]
parent  = { fg = "#cecece", bg = "#222222" }
current = { fg = "#161616", bg = "#3ba6f5" }
preview = { fg = "#cecece", bg = "#222222" }

[status]
overall = { fg = "#cecece", bg = "#121212" }

progress_label  = { fg = "#eeeeee", bold = true }
progress_normal = { fg = "#5bb661", bg = "#222222" }
progress_error  = { fg = "#c39900", bg = "#ed756e" }

perm_type  = { fg = "#3ba6f5" }
perm_read  = { fg = "#c39900" }
perm_write = { fg = "#ed756e" }
perm_exec  = { fg = "#5bb661" }
perm_sep   = { fg = "#555555" }

[which]
mask            = { bg = "#222222" }
cand            = { fg = "#00baaa" }
rest            = { fg = "#808080" }
desc            = { fg = "#aeaeae" }
separator       = "  "
separator_style = { fg = "#3a3a3a" }

[help]
on      = { fg = "#00baaa" }
run     = { fg = "#3ba6f5" }
desc    = { fg = "#808080" }
hovered = { bg = "#222222", bold = true }
footer  = { fg = "#cecece", bg = "#222222" }

[notify]
title_info  = { fg = "#3ba6f5" }
title_warn  = { fg = "#e48233" }
title_error = { fg = "#ed756e" }

[pick]
border   = { fg = "#3ba6f5" }
active   = { fg = "#eeeeee" }
inactive = { fg = "#808080" }

[input]
border   = { fg = "#3ba6f5" }
value    = { fg = "#cecece" }
selected = { reversed = true }

[confirm]
border  = { fg = "#3ba6f5" }
title   = { fg = "#3ba6f5" }
btn_yes = { reversed = true }

[cmp]
border = { fg = "#3ba6f5" }
active = { fg = "#eeeeee" }

[tasks]
border  = { fg = "#3ba6f5" }
hovered = { fg = "#eeeeee", bold = true }

[spot]
border   = { fg = "#3ba6f5" }
title    = { fg = "#3ba6f5" }
tbl_cell = { fg = "#3ba6f5", reversed = true }
tbl_col  = { bold = true }

[filetype]
rules = [
	{ mime = "image/*", fg = "#e48233" },
	{ mime = "{audio,video}/*", fg = "#968ff7" },
	{ mime = "application/*zip", fg = "#e48233" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#e48233" },
	{ mime = "application/{pdf,doc,rtf}", fg = "#5bb661" },
	{ mime = "vfs/{absent,stale}", fg = "#555555" },
	{ url = "*", is = "orphan", bg = "#ed756e" },
	{ url = "*", is = "exec", fg = "#5bb661" },
	{ url = "*", is = "dummy", bg = "#ed756e" },
	{ url = "*/", is = "dummy", bg = "#ed756e" },
	{ url = "*/", fg = "#3ba6f5" },
]
